//
// File generated by HDevelop for HALCON/.NET (C#) Version 19.11.0.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

  // Procedures 
  // Local procedures 
  public void gen_buttom_edge (HObject ho_Image, HTuple hv_CenterRow, HTuple hv_CenterCol, 
      HTuple hv_BaseRectDistRow, HTuple hv_BaseRectDistCol, HTuple hv_BasePhi, HTuple hv_ImageWidth, 
      HTuple hv_ImageHeight, HTuple hv_RotatePhi, HTuple hv_RectBasePhi, HTuple hv_MinCircleColumn, 
      HTuple hv_MaxCircleColumn, out HTuple hv_ButtomEdgeRowBegin, out HTuple hv_ButtomEdgeColBegin, 
      out HTuple hv_ButtomEdgeRowEnd, out HTuple hv_ButtomEdgeColEnd)
  {




    // Local iconic variables 

    HObject ho_Rectangle1, ho_Rectangle2, ho_RectButtomMeasureRectionAffineTrans1=null;
    HObject ho_ButtomMeasureRectRegionAffineTrans2=null, ho_Contours;
    HObject ho_ButtomEdgeContour;

    // Local control variables 

    HTuple hv_HomMat2D5 = new HTuple(), hv_RectButtomMeasureRectArea = new HTuple();
    HTuple hv_RectButtomMeasureRectRow1 = new HTuple(), hv_RectButtomMeasureRectColumn1 = new HTuple();
    HTuple hv_RectButtomMeasureRectPhi1 = new HTuple(), hv_MeasureHandle5 = new HTuple();
    HTuple hv_HomMat2D6 = new HTuple(), hv_ButtomMeasureRectArea = new HTuple();
    HTuple hv_ButtomMeasureRectRow2 = new HTuple(), hv_ButtomMeasureRectColumn2 = new HTuple();
    HTuple hv_ButtomMeasureRectPhi2 = new HTuple(), hv_MeasureHandle6 = new HTuple();
    HTuple hv_ButtomAmplitude = new HTuple(), hv_ButtomDistance = new HTuple();
    HTuple hv_ButtomMetrologyHandle = new HTuple(), hv_Index = new HTuple();
    HTuple hv_ButtomEdgeRows = new HTuple(), hv_ButtomEdgeColumns = new HTuple();
    HTuple hv_Nr = new HTuple(), hv_Nc = new HTuple(), hv_Dist = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Rectangle1);
    HOperatorSet.GenEmptyObj(out ho_Rectangle2);
    HOperatorSet.GenEmptyObj(out ho_RectButtomMeasureRectionAffineTrans1);
    HOperatorSet.GenEmptyObj(out ho_ButtomMeasureRectRegionAffineTrans2);
    HOperatorSet.GenEmptyObj(out ho_Contours);
    HOperatorSet.GenEmptyObj(out ho_ButtomEdgeContour);
    hv_ButtomEdgeRowBegin = new HTuple();
    hv_ButtomEdgeColBegin = new HTuple();
    hv_ButtomEdgeRowEnd = new HTuple();
    hv_ButtomEdgeColEnd = new HTuple();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    ho_Rectangle1.Dispose();
    HOperatorSet.GenRectangle2(out ho_Rectangle1, hv_CenterRow+hv_BaseRectDistRow, 
        hv_CenterCol-hv_BaseRectDistCol, hv_RectBasePhi, 10, 5);
    }
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    ho_Rectangle2.Dispose();
    HOperatorSet.GenRectangle2(out ho_Rectangle2, hv_CenterRow+hv_BaseRectDistRow, 
        hv_CenterCol+hv_BaseRectDistCol, hv_RectBasePhi, 10, 5);
    }

    if ((int)(new HTuple(hv_MaxCircleColumn.TupleGreater(hv_MinCircleColumn))) != 0)
    {
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_HomMat2D5.Dispose();
      HOperatorSet.VectorAngleToRigid(hv_CenterRow, hv_CenterCol, -hv_RectBasePhi, 
          hv_CenterRow, hv_CenterCol, hv_BasePhi+hv_RotatePhi, out hv_HomMat2D5);
      }
      ho_RectButtomMeasureRectionAffineTrans1.Dispose();
      HOperatorSet.AffineTransRegion(ho_Rectangle1, out ho_RectButtomMeasureRectionAffineTrans1, 
          hv_HomMat2D5, "nearest_neighbor");
      hv_RectButtomMeasureRectArea.Dispose();hv_RectButtomMeasureRectRow1.Dispose();hv_RectButtomMeasureRectColumn1.Dispose();
      HOperatorSet.AreaCenter(ho_RectButtomMeasureRectionAffineTrans1, out hv_RectButtomMeasureRectArea, 
          out hv_RectButtomMeasureRectRow1, out hv_RectButtomMeasureRectColumn1);
      hv_RectButtomMeasureRectPhi1.Dispose();
      HOperatorSet.OrientationRegion(ho_RectButtomMeasureRectionAffineTrans1, out hv_RectButtomMeasureRectPhi1);
      hv_MeasureHandle5.Dispose();
      HOperatorSet.GenMeasureRectangle2(hv_RectButtomMeasureRectRow1, hv_RectButtomMeasureRectColumn1, 
          hv_RectButtomMeasureRectPhi1, 10, 5, hv_ImageWidth, hv_ImageHeight, "bicubic", 
          out hv_MeasureHandle5);

      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_HomMat2D6.Dispose();
      HOperatorSet.VectorAngleToRigid(hv_CenterRow, hv_CenterCol, -hv_RectBasePhi, 
          hv_CenterRow, hv_CenterCol, hv_BasePhi+hv_RotatePhi, out hv_HomMat2D6);
      }
      ho_ButtomMeasureRectRegionAffineTrans2.Dispose();
      HOperatorSet.AffineTransRegion(ho_Rectangle2, out ho_ButtomMeasureRectRegionAffineTrans2, 
          hv_HomMat2D6, "nearest_neighbor");
      hv_ButtomMeasureRectArea.Dispose();hv_ButtomMeasureRectRow2.Dispose();hv_ButtomMeasureRectColumn2.Dispose();
      HOperatorSet.AreaCenter(ho_ButtomMeasureRectRegionAffineTrans2, out hv_ButtomMeasureRectArea, 
          out hv_ButtomMeasureRectRow2, out hv_ButtomMeasureRectColumn2);
      hv_ButtomMeasureRectPhi2.Dispose();
      HOperatorSet.OrientationRegion(ho_ButtomMeasureRectRegionAffineTrans2, out hv_ButtomMeasureRectPhi2);
      hv_MeasureHandle6.Dispose();
      HOperatorSet.GenMeasureRectangle2(hv_ButtomMeasureRectRow2, hv_ButtomMeasureRectColumn2, 
          hv_ButtomMeasureRectPhi2, 10, 5, hv_ImageWidth, hv_ImageHeight, "bicubic", 
          out hv_MeasureHandle6);

    }
    else
    {
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_HomMat2D5.Dispose();
      HOperatorSet.VectorAngleToRigid(hv_CenterRow, hv_CenterCol, -hv_RectBasePhi, 
          hv_CenterRow, hv_CenterCol, hv_BasePhi-hv_RotatePhi, out hv_HomMat2D5);
      }
      ho_RectButtomMeasureRectionAffineTrans1.Dispose();
      HOperatorSet.AffineTransRegion(ho_Rectangle1, out ho_RectButtomMeasureRectionAffineTrans1, 
          hv_HomMat2D5, "nearest_neighbor");
      hv_RectButtomMeasureRectArea.Dispose();hv_RectButtomMeasureRectRow1.Dispose();hv_RectButtomMeasureRectColumn1.Dispose();
      HOperatorSet.AreaCenter(ho_RectButtomMeasureRectionAffineTrans1, out hv_RectButtomMeasureRectArea, 
          out hv_RectButtomMeasureRectRow1, out hv_RectButtomMeasureRectColumn1);
      hv_RectButtomMeasureRectPhi1.Dispose();
      HOperatorSet.OrientationRegion(ho_RectButtomMeasureRectionAffineTrans1, out hv_RectButtomMeasureRectPhi1);
      hv_MeasureHandle5.Dispose();
      HOperatorSet.GenMeasureRectangle2(hv_RectButtomMeasureRectRow1, hv_RectButtomMeasureRectColumn1, 
          hv_RectButtomMeasureRectPhi1, 10, 5, hv_ImageWidth, hv_ImageHeight, "bicubic", 
          out hv_MeasureHandle5);

      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_HomMat2D6.Dispose();
      HOperatorSet.VectorAngleToRigid(hv_CenterRow, hv_CenterCol, -hv_RectBasePhi, 
          hv_CenterRow, hv_CenterCol, hv_BasePhi-hv_RotatePhi, out hv_HomMat2D6);
      }
      ho_ButtomMeasureRectRegionAffineTrans2.Dispose();
      HOperatorSet.AffineTransRegion(ho_Rectangle2, out ho_ButtomMeasureRectRegionAffineTrans2, 
          hv_HomMat2D6, "nearest_neighbor");
      hv_ButtomMeasureRectArea.Dispose();hv_ButtomMeasureRectRow2.Dispose();hv_ButtomMeasureRectColumn2.Dispose();
      HOperatorSet.AreaCenter(ho_ButtomMeasureRectRegionAffineTrans2, out hv_ButtomMeasureRectArea, 
          out hv_ButtomMeasureRectRow2, out hv_ButtomMeasureRectColumn2);
      hv_ButtomMeasureRectPhi2.Dispose();
      HOperatorSet.OrientationRegion(ho_ButtomMeasureRectRegionAffineTrans2, out hv_ButtomMeasureRectPhi2);
      hv_MeasureHandle6.Dispose();
      HOperatorSet.GenMeasureRectangle2(hv_ButtomMeasureRectRow2, hv_ButtomMeasureRectColumn2, 
          hv_ButtomMeasureRectPhi2, 10, 5, hv_ImageWidth, hv_ImageHeight, "bicubic", 
          out hv_MeasureHandle6);

    }
    //抓取边缘
    hv_ButtomEdgeRowBegin.Dispose();hv_ButtomEdgeColBegin.Dispose();hv_ButtomAmplitude.Dispose();hv_ButtomDistance.Dispose();
    HOperatorSet.MeasurePos(ho_Image, hv_MeasureHandle5, 1, 150, "all", "first", 
        out hv_ButtomEdgeRowBegin, out hv_ButtomEdgeColBegin, out hv_ButtomAmplitude, 
        out hv_ButtomDistance);
    hv_ButtomEdgeRowEnd.Dispose();hv_ButtomEdgeColEnd.Dispose();hv_ButtomAmplitude.Dispose();hv_ButtomDistance.Dispose();
    HOperatorSet.MeasurePos(ho_Image, hv_MeasureHandle6, 1, 150, "all", "first", 
        out hv_ButtomEdgeRowEnd, out hv_ButtomEdgeColEnd, out hv_ButtomAmplitude, 
        out hv_ButtomDistance);

    HOperatorSet.CloseMeasure(hv_MeasureHandle5);
    HOperatorSet.CloseMeasure(hv_MeasureHandle6);

    //拟合边缘
    hv_ButtomMetrologyHandle.Dispose();
    HOperatorSet.CreateMetrologyModel(out hv_ButtomMetrologyHandle);
    hv_Index.Dispose();
    HOperatorSet.AddMetrologyObjectLineMeasure(hv_ButtomMetrologyHandle, hv_ButtomEdgeRowBegin, 
        hv_ButtomEdgeColBegin, hv_ButtomEdgeRowEnd, hv_ButtomEdgeColEnd, 5, 1, 1, 
        150, new HTuple(), new HTuple(), out hv_Index);
    HOperatorSet.ApplyMetrologyModel(ho_Image, hv_ButtomMetrologyHandle);
    ho_Contours.Dispose();hv_ButtomEdgeRows.Dispose();hv_ButtomEdgeColumns.Dispose();
    HOperatorSet.GetMetrologyObjectMeasures(out ho_Contours, hv_ButtomMetrologyHandle, 
        "all", "all", out hv_ButtomEdgeRows, out hv_ButtomEdgeColumns);
    ho_ButtomEdgeContour.Dispose();
    HOperatorSet.GenContourPolygonXld(out ho_ButtomEdgeContour, hv_ButtomEdgeRows, 
        hv_ButtomEdgeColumns);
    hv_ButtomEdgeRowBegin.Dispose();hv_ButtomEdgeColBegin.Dispose();hv_ButtomEdgeRowEnd.Dispose();hv_ButtomEdgeColEnd.Dispose();hv_Nr.Dispose();hv_Nc.Dispose();hv_Dist.Dispose();
    HOperatorSet.FitLineContourXld(ho_ButtomEdgeContour, "drop", -1, 0, 5, 4, out hv_ButtomEdgeRowBegin, 
        out hv_ButtomEdgeColBegin, out hv_ButtomEdgeRowEnd, out hv_ButtomEdgeColEnd, 
        out hv_Nr, out hv_Nc, out hv_Dist);


    ho_Rectangle1.Dispose();
    ho_Rectangle2.Dispose();
    ho_RectButtomMeasureRectionAffineTrans1.Dispose();
    ho_ButtomMeasureRectRegionAffineTrans2.Dispose();
    ho_Contours.Dispose();
    ho_ButtomEdgeContour.Dispose();

    hv_HomMat2D5.Dispose();
    hv_RectButtomMeasureRectArea.Dispose();
    hv_RectButtomMeasureRectRow1.Dispose();
    hv_RectButtomMeasureRectColumn1.Dispose();
    hv_RectButtomMeasureRectPhi1.Dispose();
    hv_MeasureHandle5.Dispose();
    hv_HomMat2D6.Dispose();
    hv_ButtomMeasureRectArea.Dispose();
    hv_ButtomMeasureRectRow2.Dispose();
    hv_ButtomMeasureRectColumn2.Dispose();
    hv_ButtomMeasureRectPhi2.Dispose();
    hv_MeasureHandle6.Dispose();
    hv_ButtomAmplitude.Dispose();
    hv_ButtomDistance.Dispose();
    hv_ButtomMetrologyHandle.Dispose();
    hv_Index.Dispose();
    hv_ButtomEdgeRows.Dispose();
    hv_ButtomEdgeColumns.Dispose();
    hv_Nr.Dispose();
    hv_Nc.Dispose();
    hv_Dist.Dispose();

    return;
  }

  public void gen_FitPoint (HObject ho_Image, out HObject ho_Circle1, HTuple hv_Origin_Row_InImg, 
      HTuple hv_Origin_Column_InImg, HTuple hv_TwoCirclePhi, HTuple hv_p_XOffest, 
      HTuple hv_p_YOffest, HTuple hv_MaxCircleColumn, HTuple hv_MinCircleColumn, HTuple hv_MaxCircleRow, 
      HTuple hv_Width, HTuple hv_Height, out HTuple hv_p_x, out HTuple hv_p_y, out HTuple hv_p_x_fit, 
      out HTuple hv_p_y_fit)
  {




    // Local iconic variables 

    // Local control variables 

    HTuple hv_HomMat2D_Img2Base = new HTuple();
    HTuple hv_Origin_Column_InBase = new HTuple(), hv_Origin_Row_InBase = new HTuple();
    HTuple hv_p_XInBase = new HTuple(), hv_p_YInBase = new HTuple();
    HTuple hv_HomMat2D_Base2Img = new HTuple(), hv_MeasureRectPhi1 = new HTuple();
    HTuple hv_MeasureHandle1 = new HTuple(), hv_Amplitude = new HTuple();
    HTuple hv_Distance = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Circle1);
    hv_p_x = new HTuple();
    hv_p_y = new HTuple();
    hv_p_x_fit = new HTuple();
    hv_p_y_fit = new HTuple();
    //计算图像坐标系到基准坐标系的变换矩阵
    hv_HomMat2D_Img2Base.Dispose();
    HOperatorSet.VectorAngleToRigid(0, 0, 0, hv_Origin_Row_InImg, hv_Origin_Column_InImg, 
        hv_TwoCirclePhi, out hv_HomMat2D_Img2Base);
    //将图像坐标系下的基准点转换到基准坐标系下
    hv_Origin_Column_InBase.Dispose();hv_Origin_Row_InBase.Dispose();
    HOperatorSet.AffineTransPoint2d(hv_HomMat2D_Img2Base, hv_Origin_Column_InImg, 
        hv_Origin_Row_InImg, out hv_Origin_Column_InBase, out hv_Origin_Row_InBase);
    //在基准坐标系下对基准点进行偏移找拟合点
    if ((int)(new HTuple(hv_MaxCircleColumn.TupleLess(hv_MinCircleColumn))) != 0)
    {
      hv_p_XInBase.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_p_XInBase = hv_Origin_Column_InBase-hv_p_XOffest;
      }
      hv_p_YInBase.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_p_YInBase = hv_Origin_Row_InBase-hv_p_YOffest;
      }
    }
    else
    {
      hv_p_XInBase.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_p_XInBase = hv_Origin_Column_InBase+hv_p_XOffest;
      }
      hv_p_YInBase.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_p_YInBase = hv_Origin_Row_InBase+hv_p_YOffest;
      }
    }

    //计算基准坐标系到图像坐标系下的变换矩阵
    hv_HomMat2D_Base2Img.Dispose();
    HOperatorSet.HomMat2dInvert(hv_HomMat2D_Img2Base, out hv_HomMat2D_Base2Img);
    //将基准坐标系下的拟合点转换到图像坐标系下
    hv_p_x_fit.Dispose();hv_p_y_fit.Dispose();
    HOperatorSet.AffineTransPoint2d(hv_HomMat2D_Base2Img, hv_p_XInBase, hv_p_YInBase, 
        out hv_p_x_fit, out hv_p_y_fit);

    //**********如采用边缘点则取消注释*******************
    //p_x := p_x_fit
    //p_y := p_y_fit
    //**************************************************


    //**********如直接采用手册标记点则取消注释*******************
    hv_MeasureRectPhi1.Dispose();
    HOperatorSet.LineOrientation(hv_MaxCircleRow, hv_MaxCircleColumn, hv_p_y_fit, 
        hv_p_x_fit, out hv_MeasureRectPhi1);
    hv_MeasureHandle1.Dispose();
    HOperatorSet.GenMeasureRectangle2(hv_p_y_fit, hv_p_x_fit, hv_MeasureRectPhi1, 
        30, 2, hv_Width, hv_Height, "bicubic", out hv_MeasureHandle1);
    hv_p_y.Dispose();hv_p_x.Dispose();hv_Amplitude.Dispose();hv_Distance.Dispose();
    HOperatorSet.MeasurePos(ho_Image, hv_MeasureHandle1, 1.5, 50, "all", "all", out hv_p_y, 
        out hv_p_x, out hv_Amplitude, out hv_Distance);
    HOperatorSet.CloseMeasure(hv_MeasureHandle1);
    //*********************************************************
    ho_Circle1.Dispose();
    HOperatorSet.GenCircle(out ho_Circle1, hv_p_y, hv_p_x, 10);

    hv_HomMat2D_Img2Base.Dispose();
    hv_Origin_Column_InBase.Dispose();
    hv_Origin_Row_InBase.Dispose();
    hv_p_XInBase.Dispose();
    hv_p_YInBase.Dispose();
    hv_HomMat2D_Base2Img.Dispose();
    hv_MeasureRectPhi1.Dispose();
    hv_MeasureHandle1.Dispose();
    hv_Amplitude.Dispose();
    hv_Distance.Dispose();

    return;
  }

  public void gen_TwoCircle_info_3D (HObject ho_Image, out HTuple hv_MaxCircleRow, out HTuple hv_MaxCircleColumn, 
      out HTuple hv_MaxCircleRadius, out HTuple hv_MinCircleRow, out HTuple hv_MinCircleColumn, 
      out HTuple hv_MinCircleRadius, out HTuple hv_TwoCirclePhi)
  {



    // Local iconic variables 

    HObject ho_Regions, ho_ConnectedRegions, ho_MaxCircleSelectedRegions;
    HObject ho_MinCircleSelectedRegions, ho_MinCircle, ho_MaxCircle;
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Regions);
    HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
    HOperatorSet.GenEmptyObj(out ho_MaxCircleSelectedRegions);
    HOperatorSet.GenEmptyObj(out ho_MinCircleSelectedRegions);
    HOperatorSet.GenEmptyObj(out ho_MinCircle);
    HOperatorSet.GenEmptyObj(out ho_MaxCircle);
    hv_MaxCircleRow = new HTuple();
    hv_MaxCircleColumn = new HTuple();
    hv_MaxCircleRadius = new HTuple();
    hv_MinCircleRow = new HTuple();
    hv_MinCircleColumn = new HTuple();
    hv_MinCircleRadius = new HTuple();
    hv_TwoCirclePhi = new HTuple();
    //fast_threshold (Image, Regions, 128, 255, 20)

    //threshold (Image, Regions, 152, 181)

    ho_Regions.Dispose();
    HOperatorSet.AutoThreshold(ho_Image, out ho_Regions, 0.2);
    ho_ConnectedRegions.Dispose();
    HOperatorSet.Connection(ho_Regions, out ho_ConnectedRegions);
    //提取两个圆形区域

    ho_MaxCircleSelectedRegions.Dispose();
    HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_MaxCircleSelectedRegions, 
        (new HTuple("area")).TupleConcat("circularity"), "and", (new HTuple(217996)).TupleConcat(
        0.7004), (new HTuple(1.24768e+06)).TupleConcat(0.7301));
    ho_MinCircleSelectedRegions.Dispose();
    HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_MinCircleSelectedRegions, 
        (new HTuple("area")).TupleConcat("circularity"), "and", (new HTuple(217996)).TupleConcat(
        0.7579), (new HTuple(1.24768e+06)).TupleConcat(0.8006));

    hv_MaxCircleRow.Dispose();hv_MaxCircleColumn.Dispose();hv_MaxCircleRadius.Dispose();
    HOperatorSet.SmallestCircle(ho_MaxCircleSelectedRegions, out hv_MaxCircleRow, 
        out hv_MaxCircleColumn, out hv_MaxCircleRadius);
    hv_MinCircleRow.Dispose();hv_MinCircleColumn.Dispose();hv_MinCircleRadius.Dispose();
    HOperatorSet.SmallestCircle(ho_MinCircleSelectedRegions, out hv_MinCircleRow, 
        out hv_MinCircleColumn, out hv_MinCircleRadius);

    ho_MinCircle.Dispose();
    HOperatorSet.GenCircleContourXld(out ho_MinCircle, hv_MinCircleRow, hv_MinCircleColumn, 
        hv_MinCircleRadius, 0, 6.28318, "positive", 1);
    ho_MaxCircle.Dispose();
    HOperatorSet.GenCircleContourXld(out ho_MaxCircle, hv_MaxCircleRow, hv_MaxCircleColumn, 
        hv_MaxCircleRadius, 0, 6.28318, "positive", 1);


    //求两圆心连线方向
    hv_TwoCirclePhi.Dispose();
    HOperatorSet.LineOrientation(hv_MaxCircleRow, hv_MaxCircleColumn, hv_MinCircleRow, 
        hv_MinCircleColumn, out hv_TwoCirclePhi);



    //threshold_sub_pix (Image, Border, 1)
    //select_shape_xld (Border, MinCircleContour, 'area', 'and', 463303, 766055)
    //fit_circle_contour_xld (MinCircleContour, 'algebraic', -1, 0, 0, 3, 2, MinCircleRow, MinCircleColumn, MinCircleRadius, StartPhi, EndPhi, PointOrder)
    //select_shape_xld (Border, MaxCircleContour, 'area', 'and', 738532, 1.03211e+06)
    //fit_circle_contour_xld (MaxCircleContour, 'algebraic', -1, 0, 0, 3, 2, MaxCircleRow, MaxCircleColumn, MaxCircleRadius, StartPhi, EndPhi, PointOrder)
    //line_orientation (MaxCircleRow, MaxCircleColumn, MinCircleRow, MinCircleColumn, TwoCirclePhi)

    ho_Regions.Dispose();
    ho_ConnectedRegions.Dispose();
    ho_MaxCircleSelectedRegions.Dispose();
    ho_MinCircleSelectedRegions.Dispose();
    ho_MinCircle.Dispose();
    ho_MaxCircle.Dispose();


    return;
  }

  public void my_create_coordinate (HTuple hv_HomMat2DIdentity, HTuple hv_Col_Origin, 
      HTuple hv_Row_Origin, HTuple hv_ColEnd_X, HTuple hv_RowEnd_X, out HTuple hv_Phi, 
      out HTuple hv_ColEnd_Y, out HTuple hv_RowEnd_Y)
  {



    // Local control variables 

    HTuple hv_HomMat2DRotate = new HTuple();
    // Initialize local and output iconic variables 
    hv_Phi = new HTuple();
    hv_ColEnd_Y = new HTuple();
    hv_RowEnd_Y = new HTuple();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_HomMat2DRotate.Dispose();
    HOperatorSet.HomMat2dRotate(hv_HomMat2DIdentity, (new HTuple(-90)).TupleRad()
        , hv_Col_Origin, hv_Row_Origin, out hv_HomMat2DRotate);
    }
    hv_ColEnd_Y.Dispose();hv_RowEnd_Y.Dispose();
    HOperatorSet.AffineTransPoint2d(hv_HomMat2DRotate, hv_ColEnd_X, hv_RowEnd_X, 
        out hv_ColEnd_Y, out hv_RowEnd_Y);
    hv_Phi.Dispose();
    HOperatorSet.LineOrientation(hv_Row_Origin, hv_Col_Origin, hv_RowEnd_X, hv_ColEnd_X, 
        out hv_Phi);

    hv_HomMat2DRotate.Dispose();

    return;
  }

  public void my_fit_surface (HObject ho_ImageZ, HTuple hv_HomMat2DIdentity, HTuple hv_p_A1_x_offest, 
      HTuple hv_p_A1_y_offest, HTuple hv_Phi, HTuple hv_Col_Origin, HTuple hv_Row_Origin, 
      HTuple hv_p_A2_x_offest, HTuple hv_p_A2_y_offest, HTuple hv_p_A3_x_offest, HTuple hv_p_A3_y_offest, 
      HTuple hv_p_A4_x_offest, HTuple hv_p_A4_y_offest, HTuple hv_p_A5_x_offest, HTuple hv_p_A5_y_offest, 
      HTuple hv_p_A6_x_offest, HTuple hv_p_A6_y_offest, HTuple hv_p_A7_x_offest, HTuple hv_p_A7_y_offest, 
      HTuple hv_p_A8_x_offest, HTuple hv_p_A8_y_offest, out HTuple hv_Z_Origin_median)
  {




    // Local iconic variables 

    // Local control variables 

    HTuple hv_p_A1_x_fit = new HTuple(), hv_p_A1_y_fit = new HTuple();
    HTuple hv_p_A2_x_fit = new HTuple(), hv_p_A2_y_fit = new HTuple();
    HTuple hv_p_A3_x_fit = new HTuple(), hv_p_A3_y_fit = new HTuple();
    HTuple hv_p_A4_x_fit = new HTuple(), hv_p_A4_y_fit = new HTuple();
    HTuple hv_p_A5_x_fit = new HTuple(), hv_p_A5_y_fit = new HTuple();
    HTuple hv_p_A6_x_fit = new HTuple(), hv_p_A6_y_fit = new HTuple();
    HTuple hv_p_A7_x_fit = new HTuple(), hv_p_A7_y_fit = new HTuple();
    HTuple hv_p_A8_x_fit = new HTuple(), hv_p_A8_y_fit = new HTuple();
    HTuple hv_Surface_Zs = new HTuple(), hv_Z_Origin_NoMaxMin = new HTuple();
    HTuple hv_Index = new HTuple();
    // Initialize local and output iconic variables 
    hv_Z_Origin_median = new HTuple();
    //定位8个给定平面拟合点
    hv_p_A1_x_fit.Dispose();hv_p_A1_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_A1_x_offest, 
        hv_p_A1_y_offest, out hv_p_A1_x_fit, out hv_p_A1_y_fit);
    hv_p_A2_x_fit.Dispose();hv_p_A2_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_A2_x_offest, 
        hv_p_A2_y_offest, out hv_p_A2_x_fit, out hv_p_A2_y_fit);
    hv_p_A3_x_fit.Dispose();hv_p_A3_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_A3_x_offest, 
        hv_p_A3_y_offest, out hv_p_A3_x_fit, out hv_p_A3_y_fit);
    hv_p_A4_x_fit.Dispose();hv_p_A4_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_A4_x_offest, 
        hv_p_A4_y_offest, out hv_p_A4_x_fit, out hv_p_A4_y_fit);
    hv_p_A5_x_fit.Dispose();hv_p_A5_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_A5_x_offest, 
        hv_p_A5_y_offest, out hv_p_A5_x_fit, out hv_p_A5_y_fit);
    hv_p_A6_x_fit.Dispose();hv_p_A6_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_A6_x_offest, 
        hv_p_A6_y_offest, out hv_p_A6_x_fit, out hv_p_A6_y_fit);
    hv_p_A7_x_fit.Dispose();hv_p_A7_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_A7_x_offest, 
        hv_p_A7_y_offest, out hv_p_A7_x_fit, out hv_p_A7_y_fit);
    hv_p_A8_x_fit.Dispose();hv_p_A8_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_A8_x_offest, 
        hv_p_A8_y_offest, out hv_p_A8_x_fit, out hv_p_A8_y_fit);

    //获取八个平面拟合点的灰度值，即Z向距离
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_Surface_Zs.Dispose();
    HOperatorSet.GetGrayvalInterpolated(ho_ImageZ, ((((((((((((hv_p_A1_y_fit.TupleConcat(
        hv_p_A2_y_fit))).TupleConcat(hv_p_A3_y_fit))).TupleConcat(hv_p_A4_y_fit))).TupleConcat(
        hv_p_A5_y_fit))).TupleConcat(hv_p_A6_y_fit))).TupleConcat(hv_p_A7_y_fit))).TupleConcat(
        hv_p_A8_y_fit), ((((((((((((hv_p_A1_x_fit.TupleConcat(hv_p_A2_x_fit))).TupleConcat(
        hv_p_A3_x_fit))).TupleConcat(hv_p_A4_x_fit))).TupleConcat(hv_p_A5_x_fit))).TupleConcat(
        hv_p_A6_x_fit))).TupleConcat(hv_p_A7_x_fit))).TupleConcat(hv_p_A8_x_fit), 
        "bicubic_clipped", out hv_Surface_Zs);
    }

    //根据八个平面拟合点，获取八个Z向值，去除最大最小值干扰后求取中位值
    //将中位值作为Z向0点
    //tuple_max (Surface_Zs, Z_Origin_Max)
    //tuple_min (Surface_Zs, Z_Origin_Min)
    hv_Z_Origin_NoMaxMin.Dispose();
    hv_Z_Origin_NoMaxMin = new HTuple();
    for (hv_Index=0; (int)hv_Index<=(int)((new HTuple(hv_Surface_Zs.TupleLength()
        ))-1); hv_Index = (int)hv_Index + 1)
    {
      //if (Surface_Zs[Index] != Z_Origin_Max and Surface_Zs[Index] != Z_Origin_Min)
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
        {
        HTuple 
          ExpTmpLocalVar_Z_Origin_NoMaxMin = hv_Z_Origin_NoMaxMin.TupleConcat(
            (((hv_Surface_Zs.TupleSelect(hv_Index))-32768)*1.6)/1000);
        hv_Z_Origin_NoMaxMin.Dispose();
        hv_Z_Origin_NoMaxMin = ExpTmpLocalVar_Z_Origin_NoMaxMin;
        }
        }
      //endif
    }
    hv_Z_Origin_median.Dispose();
    HOperatorSet.TupleMean(hv_Z_Origin_NoMaxMin, out hv_Z_Origin_median);

    hv_p_A1_x_fit.Dispose();
    hv_p_A1_y_fit.Dispose();
    hv_p_A2_x_fit.Dispose();
    hv_p_A2_y_fit.Dispose();
    hv_p_A3_x_fit.Dispose();
    hv_p_A3_y_fit.Dispose();
    hv_p_A4_x_fit.Dispose();
    hv_p_A4_y_fit.Dispose();
    hv_p_A5_x_fit.Dispose();
    hv_p_A5_y_fit.Dispose();
    hv_p_A6_x_fit.Dispose();
    hv_p_A6_y_fit.Dispose();
    hv_p_A7_x_fit.Dispose();
    hv_p_A7_y_fit.Dispose();
    hv_p_A8_x_fit.Dispose();
    hv_p_A8_y_fit.Dispose();
    hv_Surface_Zs.Dispose();
    hv_Z_Origin_NoMaxMin.Dispose();
    hv_Index.Dispose();

    return;
  }

  public void my_gen_4point_offest (HObject ho_ImageZ, HTuple hv_HomMat2DIdentity, 
      HTuple hv_p_E2_x_offest, HTuple hv_p_E2_y_offest, HTuple hv_Phi, HTuple hv_Col_Origin, 
      HTuple hv_Row_Origin, HTuple hv_p_E5_x_offest, HTuple hv_p_E5_y_offest, HTuple hv_p_E10_x_offest, 
      HTuple hv_p_E10_y_offest, HTuple hv_p_E13_x_offest, HTuple hv_p_E13_y_offest, 
      HTuple hv_Z_Origin_Mean, out HTuple hv_E2_Z_mm, out HTuple hv_E5_Z_mm, out HTuple hv_E10_Z_mm, 
      out HTuple hv_E13_Z_mm, out HTuple hv_p_E2_x_fit, out HTuple hv_p_E2_y_fit, 
      out HTuple hv_p_E5_x_fit, out HTuple hv_p_E5_y_fit, out HTuple hv_p_E10_x_fit, 
      out HTuple hv_p_E10_y_fit, out HTuple hv_p_E13_x_fit, out HTuple hv_p_E13_y_fit)
  {




    // Local iconic variables 

    // Local control variables 

    HTuple hv_E2_Z_um = new HTuple(), hv_E5_Z_um = new HTuple();
    HTuple hv_E10_Z_um = new HTuple(), hv_E13_Z_um = new HTuple();
    // Initialize local and output iconic variables 
    hv_E2_Z_mm = new HTuple();
    hv_E5_Z_mm = new HTuple();
    hv_E10_Z_mm = new HTuple();
    hv_E13_Z_mm = new HTuple();
    hv_p_E2_x_fit = new HTuple();
    hv_p_E2_y_fit = new HTuple();
    hv_p_E5_x_fit = new HTuple();
    hv_p_E5_y_fit = new HTuple();
    hv_p_E10_x_fit = new HTuple();
    hv_p_E10_y_fit = new HTuple();
    hv_p_E13_x_fit = new HTuple();
    hv_p_E13_y_fit = new HTuple();
    hv_p_E2_x_fit.Dispose();hv_p_E2_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_E2_x_offest, 
        hv_p_E2_y_offest, out hv_p_E2_x_fit, out hv_p_E2_y_fit);
    hv_p_E5_x_fit.Dispose();hv_p_E5_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_E5_x_offest, 
        hv_p_E5_y_offest, out hv_p_E5_x_fit, out hv_p_E5_y_fit);
    hv_p_E10_x_fit.Dispose();hv_p_E10_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_E10_x_offest, 
        hv_p_E10_y_offest, out hv_p_E10_x_fit, out hv_p_E10_y_fit);
    hv_p_E13_x_fit.Dispose();hv_p_E13_y_fit.Dispose();
    my_gen_suffce_fit_point(hv_Row_Origin, hv_Col_Origin, hv_Phi, hv_p_E13_x_offest, 
        hv_p_E13_y_offest, out hv_p_E13_x_fit, out hv_p_E13_y_fit);

    //计算四个底部点相对于Z向0平面的Z向偏差
    hv_E2_Z_um.Dispose();
    HOperatorSet.GetGrayval(ho_ImageZ, hv_p_E2_y_fit, hv_p_E2_x_fit, out hv_E2_Z_um);
    hv_E2_Z_mm.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_E2_Z_mm = (((hv_E2_Z_um-32768)*1.6)/1000)-hv_Z_Origin_Mean;
    }

    hv_E5_Z_um.Dispose();
    HOperatorSet.GetGrayval(ho_ImageZ, hv_p_E5_y_fit, hv_p_E5_x_fit, out hv_E5_Z_um);
    hv_E5_Z_mm.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_E5_Z_mm = (((hv_E5_Z_um-32768)*1.6)/1000)-hv_Z_Origin_Mean;
    }

    hv_E10_Z_um.Dispose();
    HOperatorSet.GetGrayval(ho_ImageZ, hv_p_E10_y_fit, hv_p_E10_x_fit, out hv_E10_Z_um);
    hv_E10_Z_mm.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_E10_Z_mm = (((hv_E10_Z_um-32768)*1.6)/1000)-hv_Z_Origin_Mean;
    }

    hv_E13_Z_um.Dispose();
    HOperatorSet.GetGrayval(ho_ImageZ, hv_p_E13_y_fit, hv_p_E13_x_fit, out hv_E13_Z_um);
    hv_E13_Z_mm.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_E13_Z_mm = (((hv_E13_Z_um-32768)*1.6)/1000)-hv_Z_Origin_Mean;
    }

    hv_E2_Z_um.Dispose();
    hv_E5_Z_um.Dispose();
    hv_E10_Z_um.Dispose();
    hv_E13_Z_um.Dispose();

    return;
  }

  public void my_gen_result (HTuple hv_E2_Z_mm, HTuple hv_E5_Z_mm, HTuple hv_E10_Z_mm, 
      HTuple hv_E13_Z_mm, out HTuple hv_result)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_Max = new HTuple(), hv_Min = new HTuple();
    // Initialize local and output iconic variables 
    hv_result = new HTuple();
    hv_Max.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_Max = ((((((((((2.612+hv_E2_Z_mm)).TupleAbs()
        )).TupleConcat(((2.612+hv_E5_Z_mm)).TupleAbs()))).TupleConcat(((2.612+hv_E10_Z_mm)).TupleAbs()
        ))).TupleConcat(((2.612+hv_E13_Z_mm)).TupleAbs()))).TupleMax();
    }
    hv_Min.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_Min = ((((((((((2.612+hv_E2_Z_mm)).TupleAbs()
        )).TupleConcat(((2.612+hv_E5_Z_mm)).TupleAbs()))).TupleConcat(((2.612+hv_E10_Z_mm)).TupleAbs()
        ))).TupleConcat(((2.612+hv_E13_Z_mm)).TupleAbs()))).TupleMin();
    }
    //result := 2*max([Max,Min])-0.2
    hv_result.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_result = (2*(((hv_Max.TupleConcat(
        hv_Min))).TupleMax()))-0.04;
    }


    hv_Max.Dispose();
    hv_Min.Dispose();

    return;
  }

  public void my_gen_suffce_fit_point (HTuple hv_Row_Origin, HTuple hv_Col_Origin, 
      HTuple hv_Phi, HTuple hv_p_A1_x_offest, HTuple hv_p_A1_y_offest, out HTuple hv_p_A_x_fit, 
      out HTuple hv_p_A_y_fit)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_HomMat2D_Img2Base = new HTuple();
    HTuple hv_Col_Origin_InBase = new HTuple(), hv_Row_Origin_InBase = new HTuple();
    HTuple hv_p_A_XInBase = new HTuple(), hv_p_A_YInBase = new HTuple();
    HTuple hv_HomMat2D_Base2Img = new HTuple();
    // Initialize local and output iconic variables 
    hv_p_A_x_fit = new HTuple();
    hv_p_A_y_fit = new HTuple();
    //计算图像坐标系到基准坐标系的变换矩阵
    hv_HomMat2D_Img2Base.Dispose();
    HOperatorSet.VectorAngleToRigid(0, 0, 0, hv_Row_Origin, hv_Col_Origin, hv_Phi, 
        out hv_HomMat2D_Img2Base);
    //将图像坐标系下的基准点转换到基准坐标系下
    hv_Col_Origin_InBase.Dispose();hv_Row_Origin_InBase.Dispose();
    HOperatorSet.AffineTransPoint2d(hv_HomMat2D_Img2Base, hv_Col_Origin, hv_Row_Origin, 
        out hv_Col_Origin_InBase, out hv_Row_Origin_InBase);
    //在基准坐标系下对基准点进行偏移找拟合点
    hv_p_A_XInBase.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A_XInBase = hv_Col_Origin_InBase+hv_p_A1_x_offest;
    }
    hv_p_A_YInBase.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A_YInBase = (hv_Row_Origin_InBase-hv_p_A1_y_offest)-20;
    }
    //计算基准坐标系到图像坐标系下的变换矩阵
    hv_HomMat2D_Base2Img.Dispose();
    HOperatorSet.HomMat2dInvert(hv_HomMat2D_Img2Base, out hv_HomMat2D_Base2Img);
    //将基准坐标系下的拟合点转换到图像坐标系下
    hv_p_A_x_fit.Dispose();hv_p_A_y_fit.Dispose();
    HOperatorSet.AffineTransPoint2d(hv_HomMat2D_Base2Img, hv_p_A_XInBase, hv_p_A_YInBase, 
        out hv_p_A_x_fit, out hv_p_A_y_fit);

    hv_HomMat2D_Img2Base.Dispose();
    hv_Col_Origin_InBase.Dispose();
    hv_Row_Origin_InBase.Dispose();
    hv_p_A_XInBase.Dispose();
    hv_p_A_YInBase.Dispose();
    hv_HomMat2D_Base2Img.Dispose();

    return;
  }

  public void Set_Offest_Param (out HTuple hv_p_A1_x_offest, out HTuple hv_p_A1_y_offest, 
      out HTuple hv_p_A2_y_offest, out HTuple hv_p_A2_x_offest, out HTuple hv_p_A3_y_offest, 
      out HTuple hv_p_A3_x_offest, out HTuple hv_p_A4_y_offest, out HTuple hv_p_A4_x_offest, 
      out HTuple hv_p_A5_y_offest, out HTuple hv_p_A5_x_offest, out HTuple hv_p_A6_y_offest, 
      out HTuple hv_p_A6_x_offest, out HTuple hv_p_A7_y_offest, out HTuple hv_p_A7_x_offest, 
      out HTuple hv_p_A8_y_offest, out HTuple hv_p_A8_x_offest, out HTuple hv_p_E2_y_offest, 
      out HTuple hv_p_E2_x_offest, out HTuple hv_p_E5_y_offest, out HTuple hv_p_E5_x_offest, 
      out HTuple hv_p_E10_y_offest, out HTuple hv_p_E10_x_offest, out HTuple hv_p_E13_y_offest, 
      out HTuple hv_p_E13_x_offest, out HTuple hv_B_offest, out HTuple hv_C_offest)
  {


    // Local iconic variables 
    // Initialize local and output iconic variables 
    hv_p_A1_x_offest = new HTuple();
    hv_p_A1_y_offest = new HTuple();
    hv_p_A2_y_offest = new HTuple();
    hv_p_A2_x_offest = new HTuple();
    hv_p_A3_y_offest = new HTuple();
    hv_p_A3_x_offest = new HTuple();
    hv_p_A4_y_offest = new HTuple();
    hv_p_A4_x_offest = new HTuple();
    hv_p_A5_y_offest = new HTuple();
    hv_p_A5_x_offest = new HTuple();
    hv_p_A6_y_offest = new HTuple();
    hv_p_A6_x_offest = new HTuple();
    hv_p_A7_y_offest = new HTuple();
    hv_p_A7_x_offest = new HTuple();
    hv_p_A8_y_offest = new HTuple();
    hv_p_A8_x_offest = new HTuple();
    hv_p_E2_y_offest = new HTuple();
    hv_p_E2_x_offest = new HTuple();
    hv_p_E5_y_offest = new HTuple();
    hv_p_E5_x_offest = new HTuple();
    hv_p_E10_y_offest = new HTuple();
    hv_p_E10_x_offest = new HTuple();
    hv_p_E13_y_offest = new HTuple();
    hv_p_E13_x_offest = new HTuple();
    hv_B_offest = new HTuple();
    hv_C_offest = new HTuple();
    hv_p_A1_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A1_x_offest = 7.12/0.0125875;
    }
    hv_p_A1_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A1_y_offest = 4.340/0.01;
    }

    hv_p_A2_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A2_x_offest = 7.12/0.0125875;
    }
    hv_p_A2_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A2_y_offest = -4.340/0.01;
    }

    hv_p_A3_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A3_x_offest = 4.540/0.0125875;
    }
    hv_p_A3_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A3_y_offest = -6.570/0.01;
    }

    hv_p_A4_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A4_x_offest = -4.540/0.0125875;
    }
    hv_p_A4_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A4_y_offest = -6.570/0.01;
    }

    hv_p_A5_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A5_x_offest = -6.940/0.0125875;
    }
    hv_p_A5_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A5_y_offest = -4.050/0.01;
    }

    hv_p_A6_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A6_x_offest = -6.940/0.0125875;
    }
    hv_p_A6_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A6_y_offest = 4.050/0.01;
    }

    hv_p_A7_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A7_x_offest = -4.540/0.0125875;
    }
    hv_p_A7_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A7_y_offest = 6.570/0.01;
    }

    hv_p_A8_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A8_x_offest = 4.540/0.0125875;
    }
    hv_p_A8_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_A8_y_offest = 6.570/0.01;
    }

    hv_p_E2_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_E2_x_offest = 5.220/0.0125875;
    }
    hv_p_E2_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_E2_y_offest = 1.520/0.01;
    }

    hv_p_E5_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_E5_x_offest = 5.220/0.0125875;
    }
    hv_p_E5_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_E5_y_offest = -1.520/0.01;
    }

    hv_p_E10_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_E10_x_offest = -5.220/0.0125875;
    }
    hv_p_E10_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_E10_y_offest = -1.520/0.01;
    }

    hv_p_E13_x_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_E13_x_offest = -5.220/0.0125875;
    }
    hv_p_E13_y_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_p_E13_y_offest = 1.520/0.01;
    }

    hv_B_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_B_offest = 6.788/0.0125875;
    }
    hv_C_offest.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_C_offest = 19.605/0.01;
    }


    return;
  }

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_ImageZ;

    // Local control variables 

    HTuple hv_p_A1_x_offest = new HTuple(), hv_p_A1_y_offest = new HTuple();
    HTuple hv_p_A2_y_offest = new HTuple(), hv_p_A2_x_offest = new HTuple();
    HTuple hv_p_A3_y_offest = new HTuple(), hv_p_A3_x_offest = new HTuple();
    HTuple hv_p_A4_y_offest = new HTuple(), hv_p_A4_x_offest = new HTuple();
    HTuple hv_p_A5_y_offest = new HTuple(), hv_p_A5_x_offest = new HTuple();
    HTuple hv_p_A6_y_offest = new HTuple(), hv_p_A6_x_offest = new HTuple();
    HTuple hv_p_A7_y_offest = new HTuple(), hv_p_A7_x_offest = new HTuple();
    HTuple hv_p_A8_y_offest = new HTuple(), hv_p_A8_x_offest = new HTuple();
    HTuple hv_p_E2_y_offest = new HTuple(), hv_p_E2_x_offest = new HTuple();
    HTuple hv_p_E5_y_offest = new HTuple(), hv_p_E5_x_offest = new HTuple();
    HTuple hv_p_E10_y_offest = new HTuple(), hv_p_E10_x_offest = new HTuple();
    HTuple hv_p_E13_y_offest = new HTuple(), hv_p_E13_x_offest = new HTuple();
    HTuple hv_B_offest = new HTuple(), hv_C_offest = new HTuple();
    HTuple hv_start_time = new HTuple(), hv_Width = new HTuple();
    HTuple hv_Height = new HTuple(), hv_Row_Origin = new HTuple();
    HTuple hv_Col_Origin = new HTuple(), hv_MaxCircleRadius = new HTuple();
    HTuple hv_RowEnd_X = new HTuple(), hv_ColEnd_X = new HTuple();
    HTuple hv_MinCircleRadius = new HTuple(), hv_TwoCirclePhi = new HTuple();
    HTuple hv_HomMat2DIdentity = new HTuple(), hv_Phi = new HTuple();
    HTuple hv_ColEnd_Y = new HTuple(), hv_RowEnd_Y = new HTuple();
    HTuple hv_Z_Origin_Median = new HTuple(), hv_E2_Z_mm = new HTuple();
    HTuple hv_E5_Z_mm = new HTuple(), hv_E10_Z_mm = new HTuple();
    HTuple hv_E13_Z_mm = new HTuple(), hv_p_E2_x_fit = new HTuple();
    HTuple hv_p_E2_y_fit = new HTuple(), hv_p_E5_x_fit = new HTuple();
    HTuple hv_p_E5_y_fit = new HTuple(), hv_p_E10_x_fit = new HTuple();
    HTuple hv_p_E10_y_fit = new HTuple(), hv_p_E13_x_fit = new HTuple();
    HTuple hv_p_E13_y_fit = new HTuple(), hv_result = new HTuple();
    HTuple hv_stop_time = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_ImageZ);
    hv_p_A1_x_offest.Dispose();hv_p_A1_y_offest.Dispose();hv_p_A2_y_offest.Dispose();hv_p_A2_x_offest.Dispose();hv_p_A3_y_offest.Dispose();hv_p_A3_x_offest.Dispose();hv_p_A4_y_offest.Dispose();hv_p_A4_x_offest.Dispose();hv_p_A5_y_offest.Dispose();hv_p_A5_x_offest.Dispose();hv_p_A6_y_offest.Dispose();hv_p_A6_x_offest.Dispose();hv_p_A7_y_offest.Dispose();hv_p_A7_x_offest.Dispose();hv_p_A8_y_offest.Dispose();hv_p_A8_x_offest.Dispose();hv_p_E2_y_offest.Dispose();hv_p_E2_x_offest.Dispose();hv_p_E5_y_offest.Dispose();hv_p_E5_x_offest.Dispose();hv_p_E10_y_offest.Dispose();hv_p_E10_x_offest.Dispose();hv_p_E13_y_offest.Dispose();hv_p_E13_x_offest.Dispose();hv_B_offest.Dispose();hv_C_offest.Dispose();
    Set_Offest_Param(out hv_p_A1_x_offest, out hv_p_A1_y_offest, out hv_p_A2_y_offest, 
        out hv_p_A2_x_offest, out hv_p_A3_y_offest, out hv_p_A3_x_offest, out hv_p_A4_y_offest, 
        out hv_p_A4_x_offest, out hv_p_A5_y_offest, out hv_p_A5_x_offest, out hv_p_A6_y_offest, 
        out hv_p_A6_x_offest, out hv_p_A7_y_offest, out hv_p_A7_x_offest, out hv_p_A8_y_offest, 
        out hv_p_A8_x_offest, out hv_p_E2_y_offest, out hv_p_E2_x_offest, out hv_p_E5_y_offest, 
        out hv_p_E5_x_offest, out hv_p_E10_y_offest, out hv_p_E10_x_offest, out hv_p_E13_y_offest, 
        out hv_p_E13_x_offest, out hv_B_offest, out hv_C_offest);
    hv_start_time.Dispose();
    HOperatorSet.CountSeconds(out hv_start_time);
    ho_ImageZ.Dispose();
    HOperatorSet.ReadImage(out ho_ImageZ, "//mac/Home/Desktop/VirtualProject/Data/3d-Image");
    hv_Width.Dispose();hv_Height.Dispose();
    HOperatorSet.GetImageSize(ho_ImageZ, out hv_Width, out hv_Height);
    //定位两圆心
    hv_Row_Origin.Dispose();hv_Col_Origin.Dispose();hv_MaxCircleRadius.Dispose();hv_RowEnd_X.Dispose();hv_ColEnd_X.Dispose();hv_MinCircleRadius.Dispose();hv_TwoCirclePhi.Dispose();
    gen_TwoCircle_info_3D(ho_ImageZ, out hv_Row_Origin, out hv_Col_Origin, out hv_MaxCircleRadius, 
        out hv_RowEnd_X, out hv_ColEnd_X, out hv_MinCircleRadius, out hv_TwoCirclePhi);
    hv_HomMat2DIdentity.Dispose();
    HOperatorSet.HomMat2dIdentity(out hv_HomMat2DIdentity);
    //以大圆圆心为原点建立坐标系
    hv_Phi.Dispose();hv_ColEnd_Y.Dispose();hv_RowEnd_Y.Dispose();
    my_create_coordinate(hv_HomMat2DIdentity, hv_Col_Origin, hv_Row_Origin, hv_ColEnd_X, 
        hv_RowEnd_X, out hv_Phi, out hv_ColEnd_Y, out hv_RowEnd_Y);
    //寻找拟合平面点，并计算Z0向平面的高度
    hv_Z_Origin_Median.Dispose();
    my_fit_surface(ho_ImageZ, hv_HomMat2DIdentity, hv_p_A1_x_offest, hv_p_A1_y_offest, 
        hv_Phi, hv_Col_Origin, hv_Row_Origin, hv_p_A2_x_offest, hv_p_A2_y_offest, 
        hv_p_A3_x_offest, hv_p_A3_y_offest, hv_p_A4_x_offest, hv_p_A4_y_offest, hv_p_A5_x_offest, 
        hv_p_A5_y_offest, hv_p_A6_x_offest, hv_p_A6_y_offest, hv_p_A7_x_offest, hv_p_A7_y_offest, 
        hv_p_A8_x_offest, hv_p_A8_y_offest, out hv_Z_Origin_Median);
    //寻找底部4个点，计算四个点相对于Z0向平面的偏差
    hv_E2_Z_mm.Dispose();hv_E5_Z_mm.Dispose();hv_E10_Z_mm.Dispose();hv_E13_Z_mm.Dispose();hv_p_E2_x_fit.Dispose();hv_p_E2_y_fit.Dispose();hv_p_E5_x_fit.Dispose();hv_p_E5_y_fit.Dispose();hv_p_E10_x_fit.Dispose();hv_p_E10_y_fit.Dispose();hv_p_E13_x_fit.Dispose();hv_p_E13_y_fit.Dispose();
    my_gen_4point_offest(ho_ImageZ, hv_HomMat2DIdentity, hv_p_E2_x_offest, hv_p_E2_y_offest, 
        hv_Phi, hv_Col_Origin, hv_Row_Origin, hv_p_E5_x_offest, hv_p_E5_y_offest, 
        hv_p_E10_x_offest, hv_p_E10_y_offest, hv_p_E13_x_offest, hv_p_E13_y_offest, 
        hv_Z_Origin_Median, out hv_E2_Z_mm, out hv_E5_Z_mm, out hv_E10_Z_mm, out hv_E13_Z_mm, 
        out hv_p_E2_x_fit, out hv_p_E2_y_fit, out hv_p_E5_x_fit, out hv_p_E5_y_fit, 
        out hv_p_E10_x_fit, out hv_p_E10_y_fit, out hv_p_E13_x_fit, out hv_p_E13_y_fit);
    //计算轮廓度
    hv_result.Dispose();
    my_gen_result(hv_E2_Z_mm, hv_E5_Z_mm, hv_E10_Z_mm, hv_E13_Z_mm, out hv_result);
    hv_stop_time.Dispose();
    HOperatorSet.CountSeconds(out hv_stop_time);

    ho_ImageZ.Dispose();

    hv_p_A1_x_offest.Dispose();
    hv_p_A1_y_offest.Dispose();
    hv_p_A2_y_offest.Dispose();
    hv_p_A2_x_offest.Dispose();
    hv_p_A3_y_offest.Dispose();
    hv_p_A3_x_offest.Dispose();
    hv_p_A4_y_offest.Dispose();
    hv_p_A4_x_offest.Dispose();
    hv_p_A5_y_offest.Dispose();
    hv_p_A5_x_offest.Dispose();
    hv_p_A6_y_offest.Dispose();
    hv_p_A6_x_offest.Dispose();
    hv_p_A7_y_offest.Dispose();
    hv_p_A7_x_offest.Dispose();
    hv_p_A8_y_offest.Dispose();
    hv_p_A8_x_offest.Dispose();
    hv_p_E2_y_offest.Dispose();
    hv_p_E2_x_offest.Dispose();
    hv_p_E5_y_offest.Dispose();
    hv_p_E5_x_offest.Dispose();
    hv_p_E10_y_offest.Dispose();
    hv_p_E10_x_offest.Dispose();
    hv_p_E13_y_offest.Dispose();
    hv_p_E13_x_offest.Dispose();
    hv_B_offest.Dispose();
    hv_C_offest.Dispose();
    hv_start_time.Dispose();
    hv_Width.Dispose();
    hv_Height.Dispose();
    hv_Row_Origin.Dispose();
    hv_Col_Origin.Dispose();
    hv_MaxCircleRadius.Dispose();
    hv_RowEnd_X.Dispose();
    hv_ColEnd_X.Dispose();
    hv_MinCircleRadius.Dispose();
    hv_TwoCirclePhi.Dispose();
    hv_HomMat2DIdentity.Dispose();
    hv_Phi.Dispose();
    hv_ColEnd_Y.Dispose();
    hv_RowEnd_Y.Dispose();
    hv_Z_Origin_Median.Dispose();
    hv_E2_Z_mm.Dispose();
    hv_E5_Z_mm.Dispose();
    hv_E10_Z_mm.Dispose();
    hv_E13_Z_mm.Dispose();
    hv_p_E2_x_fit.Dispose();
    hv_p_E2_y_fit.Dispose();
    hv_p_E5_x_fit.Dispose();
    hv_p_E5_y_fit.Dispose();
    hv_p_E10_x_fit.Dispose();
    hv_p_E10_y_fit.Dispose();
    hv_p_E13_x_fit.Dispose();
    hv_p_E13_y_fit.Dispose();
    hv_result.Dispose();
    hv_stop_time.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

