namespace LJX8_DllSampleAll.Forms
{
	partial class SettingForm
	{
		private System.ComponentModel.IContainer components = null;

		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}


		private void InitializeComponent()
		{
            this._labelHexType = new System.Windows.Forms.Label();
            this._textBoxType = new System.Windows.Forms.TextBox();
            this._labelType = new System.Windows.Forms.Label();
            this._labelCategor = new System.Windows.Forms.Label();
            this._textBoxCategor = new System.Windows.Forms.TextBox();
            this._labelHexCategor = new System.Windows.Forms.Label();
            this._labelItem = new System.Windows.Forms.Label();
            this._textBoxItem = new System.Windows.Forms.TextBox();
            this._labelHexItem = new System.Windows.Forms.Label();
            this._labelTarget1 = new System.Windows.Forms.Label();
            this._textBoxTarget1 = new System.Windows.Forms.TextBox();
            this._labelHexTarget1 = new System.Windows.Forms.Label();
            this._labelTarget2 = new System.Windows.Forms.Label();
            this._textBoxTarget2 = new System.Windows.Forms.TextBox();
            this._labelHexTarget2 = new System.Windows.Forms.Label();
            this._labelTarget3 = new System.Windows.Forms.Label();
            this._textBoxTarget3 = new System.Windows.Forms.TextBox();
            this._labelHexTarget3 = new System.Windows.Forms.Label();
            this._labelTarget4 = new System.Windows.Forms.Label();
            this._textBoxTarget4 = new System.Windows.Forms.TextBox();
            this._labelHexTarget4 = new System.Windows.Forms.Label();
            this._labelDepth = new System.Windows.Forms.Label();
            this._textBoxDepth = new System.Windows.Forms.TextBox();
            this._labelHexDepth = new System.Windows.Forms.Label();
            this._labelParameter = new System.Windows.Forms.Label();
            this._textBoxParameter = new System.Windows.Forms.TextBox();
            this._buttonCancel = new System.Windows.Forms.Button();
            this._buttonOk = new System.Windows.Forms.Button();
            this._labelDepthDescription = new System.Windows.Forms.Label();
            this._labelTypeDescription = new System.Windows.Forms.Label();
            this._labelSettingsDescription = new System.Windows.Forms.Label();
            this._textBoxDataLength = new System.Windows.Forms.TextBox();
            this._labelAmountOfData = new System.Windows.Forms.Label();
            this._labelByte = new System.Windows.Forms.Label();
            this.SuspendLayout();
            this._labelHexType.AutoSize = true;
            this._labelHexType.Location = new System.Drawing.Point(14, 106);
            this._labelHexType.Name = "_labelHexType";
            this._labelHexType.Size = new System.Drawing.Size(19, 13);
            this._labelHexType.TabIndex = 5;
            this._labelHexType.Text = "0x";
            this._textBoxType.Location = new System.Drawing.Point(37, 103);
            this._textBoxType.MaxLength = 2;
            this._textBoxType.Name = "_textBoxType";
            this._textBoxType.Size = new System.Drawing.Size(76, 21);
            this._textBoxType.TabIndex = 6;
            this._textBoxType.Text = "10";
            this._labelType.AutoSize = true;
            this._labelType.Location = new System.Drawing.Point(119, 106);
            this._labelType.Name = "_labelType";
            this._labelType.Size = new System.Drawing.Size(66, 13);
            this._labelType.TabIndex = 7;
            this._labelType.Text = "Setting type";
            this._labelCategor.AutoSize = true;
            this._labelCategor.Location = new System.Drawing.Point(119, 178);
            this._labelCategor.Name = "_labelCategor";
            this._labelCategor.Size = new System.Drawing.Size(52, 13);
            this._labelCategor.TabIndex = 11;
            this._labelCategor.Text = "Category";
            this._textBoxCategor.Location = new System.Drawing.Point(37, 174);
            this._textBoxCategor.MaxLength = 2;
            this._textBoxCategor.Name = "_textBoxCategor";
            this._textBoxCategor.Size = new System.Drawing.Size(76, 21);
            this._textBoxCategor.TabIndex = 10;
            this._textBoxCategor.Text = "00";
            this._labelHexCategor.AutoSize = true;
            this._labelHexCategor.Location = new System.Drawing.Point(14, 178);
            this._labelHexCategor.Name = "_labelHexCategor";
            this._labelHexCategor.Size = new System.Drawing.Size(19, 13);
            this._labelHexCategor.TabIndex = 9;
            this._labelHexCategor.Text = "0x";
            this._labelItem.AutoSize = true;
            this._labelItem.Location = new System.Drawing.Point(119, 209);
            this._labelItem.Name = "_labelItem";
            this._labelItem.Size = new System.Drawing.Size(64, 13);
            this._labelItem.TabIndex = 14;
            this._labelItem.Text = "Setting item";
            this._textBoxItem.Location = new System.Drawing.Point(37, 206);
            this._textBoxItem.MaxLength = 2;
            this._textBoxItem.Name = "_textBoxItem";
            this._textBoxItem.Size = new System.Drawing.Size(76, 21);
            this._textBoxItem.TabIndex = 13;
            this._textBoxItem.Text = "02";
            this._labelHexItem.AutoSize = true;
            this._labelHexItem.Location = new System.Drawing.Point(14, 209);
            this._labelHexItem.Name = "_labelHexItem";
            this._labelHexItem.Size = new System.Drawing.Size(19, 13);
            this._labelHexItem.TabIndex = 12;
            this._labelHexItem.Text = "0x";
            this._labelTarget1.AutoSize = true;
            this._labelTarget1.Location = new System.Drawing.Point(119, 241);
            this._labelTarget1.Name = "_labelTarget1";
            this._labelTarget1.Size = new System.Drawing.Size(83, 13);
            this._labelTarget1.TabIndex = 17;
            this._labelTarget1.Text = "Setting target 1";
            this._textBoxTarget1.Location = new System.Drawing.Point(37, 237);
            this._textBoxTarget1.MaxLength = 2;
            this._textBoxTarget1.Name = "_textBoxTarget1";
            this._textBoxTarget1.Size = new System.Drawing.Size(76, 21);
            this._textBoxTarget1.TabIndex = 16;
            this._textBoxTarget1.Text = "00";
            this._labelHexTarget1.AutoSize = true;
            this._labelHexTarget1.Location = new System.Drawing.Point(14, 241);
            this._labelHexTarget1.Name = "_labelHexTarget1";
            this._labelHexTarget1.Size = new System.Drawing.Size(19, 13);
            this._labelHexTarget1.TabIndex = 15;
            this._labelHexTarget1.Text = "0x";
            this._labelTarget2.AutoSize = true;
            this._labelTarget2.Location = new System.Drawing.Point(119, 272);
            this._labelTarget2.Name = "_labelTarget2";
            this._labelTarget2.Size = new System.Drawing.Size(83, 13);
            this._labelTarget2.TabIndex = 20;
            this._labelTarget2.Text = "Setting target 2";
            this._textBoxTarget2.Location = new System.Drawing.Point(37, 269);
            this._textBoxTarget2.MaxLength = 2;
            this._textBoxTarget2.Name = "_textBoxTarget2";
            this._textBoxTarget2.Size = new System.Drawing.Size(76, 21);
            this._textBoxTarget2.TabIndex = 19;
            this._textBoxTarget2.Text = "00";
            this._labelHexTarget2.AutoSize = true;
            this._labelHexTarget2.Location = new System.Drawing.Point(14, 272);
            this._labelHexTarget2.Name = "_labelHexTarget2";
            this._labelHexTarget2.Size = new System.Drawing.Size(19, 13);
            this._labelHexTarget2.TabIndex = 18;
            this._labelHexTarget2.Text = "0x";
            this._labelTarget3.AutoSize = true;
            this._labelTarget3.Location = new System.Drawing.Point(119, 303);
            this._labelTarget3.Name = "_labelTarget3";
            this._labelTarget3.Size = new System.Drawing.Size(83, 13);
            this._labelTarget3.TabIndex = 23;
            this._labelTarget3.Text = "Setting target 3";
            this._textBoxTarget3.Location = new System.Drawing.Point(37, 300);
            this._textBoxTarget3.MaxLength = 2;
            this._textBoxTarget3.Name = "_textBoxTarget3";
            this._textBoxTarget3.Size = new System.Drawing.Size(76, 21);
            this._textBoxTarget3.TabIndex = 22;
            this._textBoxTarget3.Text = "00";
            this._labelHexTarget3.AutoSize = true;
            this._labelHexTarget3.Location = new System.Drawing.Point(14, 303);
            this._labelHexTarget3.Name = "_labelHexTarget3";
            this._labelHexTarget3.Size = new System.Drawing.Size(19, 13);
            this._labelHexTarget3.TabIndex = 21;
            this._labelHexTarget3.Text = "0x";
            this._labelTarget4.AutoSize = true;
            this._labelTarget4.Location = new System.Drawing.Point(119, 335);
            this._labelTarget4.Name = "_labelTarget4";
            this._labelTarget4.Size = new System.Drawing.Size(83, 13);
            this._labelTarget4.TabIndex = 26;
            this._labelTarget4.Text = "Setting target 4";
            this._textBoxTarget4.Location = new System.Drawing.Point(37, 332);
            this._textBoxTarget4.MaxLength = 2;
            this._textBoxTarget4.Name = "_textBoxTarget4";
            this._textBoxTarget4.Size = new System.Drawing.Size(76, 21);
            this._textBoxTarget4.TabIndex = 25;
            this._textBoxTarget4.Text = "00";
            this._labelHexTarget4.AutoSize = true;
            this._labelHexTarget4.Location = new System.Drawing.Point(14, 335);
            this._labelHexTarget4.Name = "_labelHexTarget4";
            this._labelHexTarget4.Size = new System.Drawing.Size(19, 13);
            this._labelHexTarget4.TabIndex = 24;
            this._labelHexTarget4.Text = "0x";
            this._labelDepth.AutoSize = true;
            this._labelDepth.Location = new System.Drawing.Point(119, 56);
            this._labelDepth.Name = "_labelDepth";
            this._labelDepth.Size = new System.Drawing.Size(170, 13);
            this._labelDepth.TabIndex = 3;
            this._labelDepth.Text = "Get target area and setting depth";
            this._textBoxDepth.Location = new System.Drawing.Point(37, 53);
            this._textBoxDepth.MaxLength = 2;
            this._textBoxDepth.Name = "_textBoxDepth";
            this._textBoxDepth.Size = new System.Drawing.Size(76, 21);
            this._textBoxDepth.TabIndex = 2;
            this._textBoxDepth.Text = "01";
            this._labelHexDepth.AutoSize = true;
            this._labelHexDepth.Location = new System.Drawing.Point(14, 56);
            this._labelHexDepth.Name = "_labelHexDepth";
            this._labelHexDepth.Size = new System.Drawing.Size(19, 13);
            this._labelHexDepth.TabIndex = 1;
            this._labelHexDepth.Text = "0x";
            this._labelParameter.AutoSize = true;
            this._labelParameter.Location = new System.Drawing.Point(14, 389);
            this._labelParameter.Name = "_labelParameter";
            this._labelParameter.Size = new System.Drawing.Size(292, 13);
            this._labelParameter.TabIndex = 30;
            this._labelParameter.Text = "Writing parameters (comma-separated hexadecimal values)";
            this._textBoxParameter.Location = new System.Drawing.Point(16, 405);
            this._textBoxParameter.Multiline = true;
            this._textBoxParameter.Name = "_textBoxParameter";
            this._textBoxParameter.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this._textBoxParameter.Size = new System.Drawing.Size(324, 61);
            this._textBoxParameter.TabIndex = 31;
            this._textBoxParameter.Text = "3";
            this._buttonCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this._buttonCancel.Location = new System.Drawing.Point(211, 484);
            this._buttonCancel.Name = "_buttonCancel";
            this._buttonCancel.Size = new System.Drawing.Size(75, 25);
            this._buttonCancel.TabIndex = 33;
            this._buttonCancel.Text = "Cancel";
            this._buttonCancel.UseVisualStyleBackColor = true;
            this._buttonOk.DialogResult = System.Windows.Forms.DialogResult.OK;
            this._buttonOk.Location = new System.Drawing.Point(67, 484);
            this._buttonOk.Name = "_buttonOk";
            this._buttonOk.Size = new System.Drawing.Size(75, 25);
            this._buttonOk.TabIndex = 32;
            this._buttonOk.Text = "OK";
            this._buttonOk.UseVisualStyleBackColor = true;
            this._labelDepthDescription.Location = new System.Drawing.Point(20, 75);
            this._labelDepthDescription.Name = "_labelDepthDescription";
            this._labelDepthDescription.Size = new System.Drawing.Size(322, 23);
            this._labelDepthDescription.TabIndex = 4;
            this._labelDepthDescription.Text = "0: Write settings area, 1: Running settings area, 2: Save area";
            this._labelDepthDescription.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this._labelTypeDescription.Location = new System.Drawing.Point(16, 127);
            this._labelTypeDescription.Name = "_labelTypeDescription";
            this._labelTypeDescription.Size = new System.Drawing.Size(344, 38);
            this._labelTypeDescription.TabIndex = 8;
            this._labelTypeDescription.Text = "0x01: Environment settings, 0x02: Common measurement settings, 0x10: Program 0, 0" +
    "x11: Program 1, ..., 0x1F: Program 15";
            this._labelSettingsDescription.Location = new System.Drawing.Point(20, 10);
            this._labelSettingsDescription.Name = "_labelSettingsDescription";
            this._labelSettingsDescription.Size = new System.Drawing.Size(307, 30);
            this._labelSettingsDescription.TabIndex = 0;
            this._labelSettingsDescription.Text = "For details on the items that follow the category, see the tables in the communic" +
    "ation command specifications.\r\n";
            this._labelSettingsDescription.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this._textBoxDataLength.Location = new System.Drawing.Point(107, 363);
            this._textBoxDataLength.Name = "_textBoxDataLength";
            this._textBoxDataLength.Size = new System.Drawing.Size(45, 21);
            this._textBoxDataLength.TabIndex = 28;
            this._textBoxDataLength.Text = "1";
            this._labelAmountOfData.AutoSize = true;
            this._labelAmountOfData.Location = new System.Drawing.Point(14, 366);
            this._labelAmountOfData.Name = "_labelAmountOfData";
            this._labelAmountOfData.Size = new System.Drawing.Size(82, 13);
            this._labelAmountOfData.TabIndex = 27;
            this._labelAmountOfData.Text = "Amount of data";
            this._labelByte.AutoSize = true;
            this._labelByte.Location = new System.Drawing.Point(163, 366);
            this._labelByte.Name = "_labelByte";
            this._labelByte.Size = new System.Drawing.Size(31, 13);
            this._labelByte.TabIndex = 29;
            this._labelByte.Text = "BYTE";
            this.AcceptButton = this._buttonOk;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this._buttonCancel;
            this.ClientSize = new System.Drawing.Size(372, 521);
            this.Controls.Add(this._textBoxDataLength);
            this.Controls.Add(this._labelSettingsDescription);
            this.Controls.Add(this._labelTypeDescription);
            this.Controls.Add(this._labelDepthDescription);
            this.Controls.Add(this._buttonCancel);
            this.Controls.Add(this._buttonOk);
            this.Controls.Add(this._textBoxParameter);
            this.Controls.Add(this._labelParameter);
            this.Controls.Add(this._labelDepth);
            this.Controls.Add(this._textBoxDepth);
            this.Controls.Add(this._labelHexDepth);
            this.Controls.Add(this._labelByte);
            this.Controls.Add(this._labelAmountOfData);
            this.Controls.Add(this._labelTarget4);
            this.Controls.Add(this._textBoxTarget4);
            this.Controls.Add(this._labelHexTarget4);
            this.Controls.Add(this._labelTarget3);
            this.Controls.Add(this._textBoxTarget3);
            this.Controls.Add(this._labelHexTarget3);
            this.Controls.Add(this._labelTarget2);
            this.Controls.Add(this._textBoxTarget2);
            this.Controls.Add(this._labelHexTarget2);
            this.Controls.Add(this._labelTarget1);
            this.Controls.Add(this._textBoxTarget1);
            this.Controls.Add(this._labelHexTarget1);
            this.Controls.Add(this._labelItem);
            this.Controls.Add(this._textBoxItem);
            this.Controls.Add(this._labelHexItem);
            this.Controls.Add(this._labelCategor);
            this.Controls.Add(this._textBoxCategor);
            this.Controls.Add(this._labelHexCategor);
            this.Controls.Add(this._labelType);
            this.Controls.Add(this._textBoxType);
            this.Controls.Add(this._labelHexType);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "SettingForm";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Settings";
            this.ResumeLayout(false);
            this.PerformLayout();

		}


		private System.Windows.Forms.Label _labelHexType;
		private System.Windows.Forms.TextBox _textBoxType;
		private System.Windows.Forms.Label _labelType;
		private System.Windows.Forms.Label _labelCategor;
		private System.Windows.Forms.TextBox _textBoxCategor;
		private System.Windows.Forms.Label _labelHexCategor;
		private System.Windows.Forms.Label _labelItem;
		private System.Windows.Forms.TextBox _textBoxItem;
		private System.Windows.Forms.Label _labelHexItem;
		private System.Windows.Forms.Label _labelTarget1;
		private System.Windows.Forms.TextBox _textBoxTarget1;
		private System.Windows.Forms.Label _labelHexTarget1;
		private System.Windows.Forms.Label _labelTarget2;
		private System.Windows.Forms.TextBox _textBoxTarget2;
		private System.Windows.Forms.Label _labelHexTarget2;
		private System.Windows.Forms.Label _labelTarget3;
		private System.Windows.Forms.TextBox _textBoxTarget3;
		private System.Windows.Forms.Label _labelHexTarget3;
		private System.Windows.Forms.Label _labelTarget4;
		private System.Windows.Forms.TextBox _textBoxTarget4;
		private System.Windows.Forms.Label _labelHexTarget4;
		private System.Windows.Forms.Label _labelDepth;
		private System.Windows.Forms.TextBox _textBoxDepth;
		private System.Windows.Forms.Label _labelHexDepth;
		private System.Windows.Forms.Label _labelParameter;
		private System.Windows.Forms.TextBox _textBoxParameter;
		private System.Windows.Forms.Button _buttonCancel;
		private System.Windows.Forms.Button _buttonOk;
		private System.Windows.Forms.Label _labelDepthDescription;
		private System.Windows.Forms.Label _labelTypeDescription;
		private System.Windows.Forms.Label _labelSettingsDescription;
		private System.Windows.Forms.TextBox _textBoxDataLength;
		private System.Windows.Forms.Label _labelAmountOfData;
		private System.Windows.Forms.Label _labelByte;
	}
}
