//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWindow.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWindow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ChangeActiveProgram 的本地化字符串。
        /// </summary>
        internal static string IDS_CHANGE_ACTIVE_PROGRAM {
            get {
                return ResourceManager.GetString("IDS_CHANGE_ACTIVE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CheckMemoryAccess 的本地化字符串。
        /// </summary>
        internal static string IDS_CHECK_MEMORY_ACCESS {
            get {
                return ResourceManager.GetString("IDS_CHECK_MEMORY_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClearError 的本地化字符串。
        /// </summary>
        internal static string IDS_CLEAR_ERROR {
            get {
                return ResourceManager.GetString("IDS_CLEAR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClearMemory 的本地化字符串。
        /// </summary>
        internal static string IDS_CLEAR_MEMORY {
            get {
                return ResourceManager.GetString("IDS_CLEAR_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommunicationClose 的本地化字符串。
        /// </summary>
        internal static string IDS_COMM_CLOSE {
            get {
                return ResourceManager.GetString("IDS_COMM_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   {0} : {1} 的本地化字符串。
        /// </summary>
        internal static string IDS_COMMAND_RESULT_FORMAT {
            get {
                return ResourceManager.GetString("IDS_COMMAND_RESULT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ControlLaser 的本地化字符串。
        /// </summary>
        internal static string IDS_CONTROL_LASER {
            get {
                return ResourceManager.GetString("IDS_CONTROL_LASER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EthernetOpen 的本地化字符串。
        /// </summary>
        internal static string IDS_ETHERNET_OPEN {
            get {
                return ResourceManager.GetString("IDS_ETHERNET_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finalize 的本地化字符串。
        /// </summary>
        internal static string IDS_FINALIZE {
            get {
                return ResourceManager.GetString("IDS_FINALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinalizeHighSpeedDataCommunication 的本地化字符串。
        /// </summary>
        internal static string IDS_FINALIZE_HIGH_SPEED_DATA_COMMUNICATION {
            get {
                return ResourceManager.GetString("IDS_FINALIZE_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetActiveProgram 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_ACTIVE_PROGRAM {
            get {
                return ResourceManager.GetString("IDS_GET_ACTIVE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetBatchProfile 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_BATCH_PROFILE {
            get {
                return ResourceManager.GetString("IDS_GET_BATCH_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetBatchSimpleArray 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_BATCH_SIMPLE_ARRAY {
            get {
                return ResourceManager.GetString("IDS_GET_BATCH_SIMPLE_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetError 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_ERROR {
            get {
                return ResourceManager.GetString("IDS_GET_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetHeadTemperature 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_HEAD_TEMPERATURE {
            get {
                return ResourceManager.GetString("IDS_GET_HEAD_TEMPERATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetProfile 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_PROFILE {
            get {
                return ResourceManager.GetString("IDS_GET_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetSerialNumber 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("IDS_GET_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetSetting 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_SETTING {
            get {
                return ResourceManager.GetString("IDS_GET_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save to the configuration file 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_SETTING_FILE {
            get {
                return ResourceManager.GetString("IDS_GET_SETTING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetTriggerAndPulseCount 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_TRIGGER_AND_PULSE_COUNT {
            get {
                return ResourceManager.GetString("IDS_GET_TRIGGER_AND_PULSE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetVersion 的本地化字符串。
        /// </summary>
        internal static string IDS_GET_VERSION {
            get {
                return ResourceManager.GetString("IDS_GET_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialize 的本地化字符串。
        /// </summary>
        internal static string IDS_INITIALIZE {
            get {
                return ResourceManager.GetString("IDS_INITIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeHighSpeedDataCommunication 的本地化字符串。
        /// </summary>
        internal static string IDS_INITIALIZE_HIGH_SPEED_DATA_ETHERNET_COMMUNICATION {
            get {
                return ResourceManager.GetString("IDS_INITIALIZE_HIGH_SPEED_DATA_ETHERNET_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeHighSpeedDataCommunicationSimpleArray 的本地化字符串。
        /// </summary>
        internal static string IDS_INITIALIZE_HIGH_SPEED_DATA_ETHERNET_COMMUNICATION_SIMPLE_ARRAY {
            get {
                return ResourceManager.GetString("IDS_INITIALIZE_HIGH_SPEED_DATA_ETHERNET_COMMUNICATION_SIMPLE_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSetting 的本地化字符串。
        /// </summary>
        internal static string IDS_INITIALIZE_SETTING {
            get {
                return ResourceManager.GetString("IDS_INITIALIZE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] : {1}(0x{2:x4}) 的本地化字符串。
        /// </summary>
        internal static string IDS_LOG_FORMAT {
            get {
                return ResourceManager.GetString("IDS_LOG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FULL 的本地化字符串。
        /// </summary>
        internal static string IDS_MEASURE_RANGE_FULL {
            get {
                return ResourceManager.GetString("IDS_MEASURE_RANGE_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/2 的本地化字符串。
        /// </summary>
        internal static string IDS_MEASURE_RANGE_HALF {
            get {
                return ResourceManager.GetString("IDS_MEASURE_RANGE_HALF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDDLE 的本地化字符串。
        /// </summary>
        internal static string IDS_MEASURE_RANGE_MIDDLE {
            get {
                return ResourceManager.GetString("IDS_MEASURE_RANGE_MIDDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/4 的本地化字符串。
        /// </summary>
        internal static string IDS_MEASURE_RANGE_QUARTER {
            get {
                return ResourceManager.GetString("IDS_MEASURE_RANGE_QUARTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMALL 的本地化字符串。
        /// </summary>
        internal static string IDS_MEASURE_RANGE_SMALL {
            get {
                return ResourceManager.GetString("IDS_MEASURE_RANGE_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3/4 的本地化字符串。
        /// </summary>
        internal static string IDS_MEASURE_RANGE_THREE_FOURTHS {
            get {
                return ResourceManager.GetString("IDS_MEASURE_RANGE_THREE_FOURTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #Undefined RC (0x{0,0:X4}) 的本地化字符串。
        /// </summary>
        internal static string IDS_NOT_DEFINE_FROMAT {
            get {
                return ResourceManager.GetString("IDS_NOT_DEFINE_FROMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFF 的本地化字符串。
        /// </summary>
        internal static string IDS_OFF {
            get {
                return ResourceManager.GetString("IDS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ON 的本地化字符串。
        /// </summary>
        internal static string IDS_ON {
            get {
                return ResourceManager.GetString("IDS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreStartHighSpeedDataCommunication 的本地化字符串。
        /// </summary>
        internal static string IDS_PRE_START_HIGH_SPEED_DATA_COMMUNICATION {
            get {
                return ResourceManager.GetString("IDS_PRE_START_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient buffer size 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_BUFFER_SHORT {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_BUFFER_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not initialized 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_HISPEED_NO_DEVICE {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_HISPEED_NO_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already initialized 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_HISPEED_OPEN_YET {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_HISPEED_OPEN_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device not open 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_NO_DEVICE {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_NO_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No free space 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_NOMEMORY {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_NOMEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unimplemented Error 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_NOTIMPL {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_NOTIMPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open the device 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_OPEN_DEVICE {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_OPEN_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter error 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_PARAMETER {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Response reception error 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_RECEIVE {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_RECEIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command send error 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_SEND {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time out 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_TIMEOUT {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undefined error 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_ERR_UNKNOWN {
            get {
                return ResourceManager.GetString("IDS_RC_ERR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     -&gt; {0} 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_FORMAT {
            get {
                return ResourceManager.GetString("IDS_RC_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal termination 的本地化字符串。
        /// </summary>
        internal static string IDS_RC_OK {
            get {
                return ResourceManager.GetString("IDS_RC_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RebootController 的本地化字符串。
        /// </summary>
        internal static string IDS_REBOOT_CONTROLLER {
            get {
                return ResourceManager.GetString("IDS_REBOOT_CONTROLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReflectSetting 的本地化字符串。
        /// </summary>
        internal static string IDS_REFLECT_SETTING {
            get {
                return ResourceManager.GetString("IDS_REFLECT_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NG 的本地化字符串。
        /// </summary>
        internal static string IDS_RESULT_NG {
            get {
                return ResourceManager.GetString("IDS_RESULT_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string IDS_RESULT_OK {
            get {
                return ResourceManager.GetString("IDS_RESULT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReturnToFactorySetting 的本地化字符串。
        /// </summary>
        internal static string IDS_RETURN_TO_FACTORY_SETTING {
            get {
                return ResourceManager.GetString("IDS_RETURN_TO_FACTORY_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RewriteTemporarySetting 的本地化字符串。
        /// </summary>
        internal static string IDS_REWRITE_TEMPORARY_SETTING {
            get {
                return ResourceManager.GetString("IDS_REWRITE_TEMPORARY_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 100Hz 的本地化字符串。
        /// </summary>
        internal static string IDS_SAMPLING_PERIOD_100Hz {
            get {
                return ResourceManager.GetString("IDS_SAMPLING_PERIOD_100Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10Hz 的本地化字符串。
        /// </summary>
        internal static string IDS_SAMPLING_PERIOD_10Hz {
            get {
                return ResourceManager.GetString("IDS_SAMPLING_PERIOD_10Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 16kHz 的本地化字符串。
        /// </summary>
        internal static string IDS_SAMPLING_PERIOD_16kHz {
            get {
                return ResourceManager.GetString("IDS_SAMPLING_PERIOD_16kHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1kHz 的本地化字符串。
        /// </summary>
        internal static string IDS_SAMPLING_PERIOD_1kHz {
            get {
                return ResourceManager.GetString("IDS_SAMPLING_PERIOD_1kHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4kHz 的本地化字符串。
        /// </summary>
        internal static string IDS_SAMPLING_PERIOD_4kHz {
            get {
                return ResourceManager.GetString("IDS_SAMPLING_PERIOD_4kHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetSetting 的本地化字符串。
        /// </summary>
        internal static string IDS_SET_SETTING {
            get {
                return ResourceManager.GetString("IDS_SET_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read from the configuration file 的本地化字符串。
        /// </summary>
        internal static string IDS_SET_SETTING_FILE {
            get {
                return ResourceManager.GetString("IDS_SET_SETTING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartHighSpeedDataCommunication 的本地化字符串。
        /// </summary>
        internal static string IDS_START_HIGH_SPEED_DATA_COMMUNICATION {
            get {
                return ResourceManager.GetString("IDS_START_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartMeasure 的本地化字符串。
        /// </summary>
        internal static string IDS_START_MEASURE {
            get {
                return ResourceManager.GetString("IDS_START_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StopHighSpeedDataCommunication 的本地化字符串。
        /// </summary>
        internal static string IDS_STOP_HIGH_SPEED_DATA_COMMUNICATION {
            get {
                return ResourceManager.GetString("IDS_STOP_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StopMeasure 的本地化字符串。
        /// </summary>
        internal static string IDS_STOP_MEASURE {
            get {
                return ResourceManager.GetString("IDS_STOP_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/2 的本地化字符串。
        /// </summary>
        internal static string IDS_THINNING_X_2 {
            get {
                return ResourceManager.GetString("IDS_THINNING_X_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/4 的本地化字符串。
        /// </summary>
        internal static string IDS_THINNING_X_4 {
            get {
                return ResourceManager.GetString("IDS_THINNING_X_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFF 的本地化字符串。
        /// </summary>
        internal static string IDS_THINNING_X_OFF {
            get {
                return ResourceManager.GetString("IDS_THINNING_X_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TRG_ERROR_RESET 的本地化字符串。
        /// </summary>
        internal static string IDS_TRG_ERROR_RESET {
            get {
                return ResourceManager.GetString("IDS_TRG_ERROR_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger 的本地化字符串。
        /// </summary>
        internal static string IDS_TRIGGER {
            get {
                return ResourceManager.GetString("IDS_TRIGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReflectSetting 的本地化字符串。
        /// </summary>
        internal static string IDS_UPDATE_SETTING {
            get {
                return ResourceManager.GetString("IDS_UPDATE_SETTING", resourceCulture);
            }
        }
    }
}
